{{- if .Values.global.active }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "database") | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      targetPort: postgresql
{{- end }}
