global:
  applicationName: orders-service
  namespace: orders
  environment: local
  active: true
  managedBy: argocd
  labels:
    app.kubernetes.io/part-of: orders-service
    platform.hashicorp.com/phase: application-baseline
    platform.hashicorp.com/secret-state: kubernetes-secrets

images:
  application:
    repository: python
    tag: "3.13-alpine"
    pullPolicy: IfNotPresent
  postgresql:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  traefik:
    repository: traefik
    tag: "v3.6"
    pullPolicy: IfNotPresent

serviceAccount:
  create: true

secrets:
  ordersCredentials:
    create: false
    name: orders-service-vault-credentials
    apiKey: fake-local-orders-api-key
    databaseUsername: orders_user
    databasePassword: fake-local-orders-password

  externalCredentials:
    create: true
    name: external-service-credentials
    externalApiToken: fake-local-external-api-token
    
frontend:
  name: frontend-service
  replicas: 1
  port: 8080
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

orders:
  name: orders-service
  replicas: 1
  port: 8080
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

consumer:
  name: consumer-service
  replicas: 1
  port: 8080
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

postgresql:
  name: postgresql
  database: orders
  port: 5432

  service:
    type: NodePort
    nodePort: 30432

  storage:
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: traefik
  host: orders.local

traefik:
  enabled: true
  name: traefik
  serviceType: NodePort
  port: 80
  containerPort: 8000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
