{{- if .Values.global.active }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: orders-service-tls
  namespace: {{ include "orders-service.namespace" . }}
spec:
  vaultAuthRef: orders-service
  mount: pki
  role: orders-service
  commonName: orders.local
  ttl: 1h
  expiryOffset: 15m
  destination:
    create: true
    name: orders-service-tls
    type: kubernetes.io/tls
{{- end }}
