apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: external-vault
    app.kubernetes.io/component: authentication
