{{- if .Values.secrets.externalCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.externalCredentials.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "secrets") | indent 4 }}
type: Opaque
stringData:
  EXTERNAL_API_TOKEN: {{ .Values.secrets.externalCredentials.externalApiToken | quote }}
{{- end }}