{{- if .Values.secrets.ordersCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.ordersCredentials.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "secrets") | indent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.ordersCredentials.apiKey | quote }}
  DB_USERNAME: {{ .Values.secrets.ordersCredentials.databaseUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.ordersCredentials.databasePassword | quote }}
{{- end }}

{{- if .Values.secrets.externalCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.externalCredentials.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "secrets") | indent 4 }}
type: Opaque
stringData:
  EXTERNAL_API_TOKEN: {{ .Values.secrets.externalCredentials.externalApiToken | quote }}
{{- end }}