{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "frontend") | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.orders.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "orders") | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "consumer") | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "database") | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.traefik.name }}
  namespace: {{ include "orders-service.namespace" . }}
  labels:
{{ include "orders-service.componentLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "ingress") | indent 4 }}
{{- end }}
