apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: orders-service
  namespace: orders
spec:
  vaultAuthRef: orders-service
  mount: kv
  type: kv-v2
  path: orders-service
  refreshAfter: 30s

  destination:
    create: true
    name: orders-service-vault-credentials