apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: orders-service-database
  namespace: orders
spec:
  vaultAuthRef: orders-service
  mount: database
  path: creds/orders-service

  destination:
    create: true
    name: orders-service-dynamic-db
