apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault-platform
  namespace: argocd
spec:
  description: External Vault Kubernetes integration

  sourceRepos:
    - https://github.com/Leninfitfreak/Vault-Cluster.git

  destinations:
    - namespace: vault-integration
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
